name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: The version for the release e.g. 1.2.0
        required: true
      nextSnapshot:
        description: The next snapshot version e.g. 1.2.1-SNAPSHOT
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: MAVEN_OSSRH_USERNAME
          server-password: MAVEN_OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Update version in README.md
        run: |
          for file in $(find ./ -name 'README.md'); do
            sed -i "s/<version>.\+<\/version>/<version>${{ github.event.inputs.releaseVersion }}<\/version>/g" $file
          done

      - name: Set release version
        run: mvn -B --no-transfer-progress versions:set -DnewVersion=${{ github.event.inputs.releaseVersion }}

      - name: Publish to Apache Maven Central
        run: mvn -B --no-transfer-progress clean deploy -P release
        env:
          MAVEN_OSSRH_USERNAME: ${{ secrets.MAVEN_OSSRH_USERNAME }}
          MAVEN_OSSRH_PASSWORD: ${{ secrets.MAVEN_OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release ${{ github.event.inputs.releaseVersion }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.releaseVersion }}
          body: |
            Use the following dependency in your maven pom to use this library:
            
            ```xml
            <dependencies>
              <dependency>
                <groupId>de.gcoding.boot</groupId>
                <artifactId>utilities-spring-boot-starter</artifactId>
                <version>${{ github.event.inputs.releaseVersion }}</version>
              </dependency>
            </dependencies>
            ```

            ### Things that changed in this release
            ${{ steps.changelog.outputs.changelog }}

      - name: Set next snapshot version
        run: mvn -B --no-transfer-progress versions:set -DnewVersion=${{ github.event.inputs.nextSnapshot }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version to ${{ github.event.inputs.nextSnapshot }}
